### ISSUE TITLE
Not Working in Microsoft Edge Browser

### ISSUE THREAD

**Issue by ghost** [assuncaocharles/ngx-indexed-db#139] opened 2020-02-26 09:00 UTC
Ngx-Indexed-DB is not working in Edge browser, and giving below error.

![image](https://user-images.githubusercontent.com/61495744/75328416-fdd91f80-58a3-11ea-945c-355f2561ccd1.png)

**Comment by coolweb** [comment] 2020-02-28 09:00
I came accross the same issue with IE11, it's because store in IE11 and Edge doesn't implement the getAll method, the work around is to use the openCursor method and iterate the cursor.

**Comment by assuncaocharles** [comment] 2020-04-19 13:23
Fixed on version 5.0.1

**Closed as completed by assuncaocharles** 2020-04-19 13:23 UTC

**Comment by t-eichmann** [comment] 2020-06-04 12:15
I have the same problem with 5.0.4

**Comment by t-eichmann** [comment] 2020-06-05 11:48
> I have the same problem with 5.0.4

Nevermind, as it turned out our issues where caused by a not up to date Edge version.
